const DECK = [
  {
    id: "bacio-collo",
    name: "Bacio sul collo",
    zone: "collo",
    power: 10,
    text: "Labbra aperte sotto l’orecchio, un morso leggero.",
    line: "«Lì… continua.»",
    touch: "bocca",
  },
  {
    id: "respiro",
    name: "Respiro sull’orecchio",
    zone: "collo",
    power: 8,
    text: "Aria calda, quasi nessuna pressione.",
    line: "«Mi viene la pelle d’oca.»",
    touch: "bocca",
  },
  {
    id: "bocca",
    name: "Bacio in bocca",
    zone: "collo",
    power: 12,
    text: "Lingua lenta. Lei risponde.",
    line: "«Più a fondo.»",
    touch: "bocca",
  },
  {
    id: "palmo-seno",
    name: "Palmo sul seno",
    zone: "seno",
    power: 14,
    text: "Tutta la mano, pollice che gira.",
    line: "«Stringi.»",
    touch: "mano",
  },
  {
    id: "lingua-seno",
    name: "Lingua sul seno",
    zone: "seno",
    power: 16,
    text: "Umido, dal solco verso l’esterno.",
    line: "«Non staccarti.»",
    touch: "bocca",
  },
  {
    id: "capezzolo",
    name: "Capezzolo in bocca",
    zone: "capezzoli",
    power: 18,
    text: "Succhi e denti appena accennati.",
    line: "«Ah— così.»",
    touch: "bocca",
  },
  {
    id: "pizzico",
    name: "Pizzico",
    zone: "capezzoli",
    power: 15,
    text: "Due dita, ritmo. Lei inarca la schiena.",
    line: "«Ancora. Più forte.»",
    touch: "dita",
  },
  {
    id: "unghie-ventre",
    name: "Unghie sul ventre",
    zone: "ventre",
    power: 9,
    text: "Disegni lenti verso il pube, senza arrivarci.",
    line: "«Scendi.»",
    touch: "dita",
  },
  {
    id: "bacio-ombelico",
    name: "Bacio sotto l’ombelico",
    zone: "ventre",
    power: 11,
    text: "Bocca aperta, un po’ di saliva.",
    line: "«Più in basso.»",
    touch: "bocca",
  },
  {
    id: "mani-fianchi",
    name: "Mani sui fianchi",
    zone: "fianco",
    power: 10,
    text: "La tiri contro di te. Pelle su pelle.",
    line: "«Tenermi stretta.»",
    touch: "mano",
  },
  {
    id: "morso-anca",
    name: "Morso sull’anca",
    zone: "fianco",
    power: 13,
    text: "Denti e lingua a coprire il segno.",
    line: "«Segnami.»",
    touch: "bocca",
  },
  {
    id: "interno-coscia",
    name: "Interno coscia",
    zone: "coscia",
    power: 17,
    text: "Baci umidi che salgono. Lei apre le gambe.",
    line: "«Non fermarti a metà.»",
    touch: "bocca",
  },
  {
    id: "coscia-aperta",
    name: "Coscia aperta",
    zone: "coscia",
    power: 12,
    text: "Palmo che spinge il ginocchio verso fuori.",
    line: "«Guardami.»",
    touch: "mano",
  },
  {
    id: "dita-pube",
    name: "Dita sul pube",
    zone: "pube",
    power: 20,
    text: "Pressione ferma, niente fretta.",
    line: "«Dentro il ritmo, non dentro ancora.»",
    touch: "dita",
  },
  {
    id: "lingua-pube",
    name: "Lingua sul pube",
    zone: "pube",
    power: 22,
    text: "Lenta, larga, poi stretta.",
    line: "«Lì. Esatto lì.»",
    touch: "bocca",
  },
  {
    id: "due-dita",
    name: "Due dita",
    zone: "pube",
    power: 24,
    text: "Entri bagnato. Pollice sul clitoride.",
    line: "«Non togliere il pollice.»",
    touch: "dita",
  },
];
